### ISSUE TITLE
Profila isn't working on Ubuntu 24.04 and RHEL 9 (gdb 15)

### ISSUE THREAD

**Issue by itamarst** [pythonspeed/profila#12]
Ubuntu 24.04, Python 3.12 and 3.11. Looks as if... debuginfo isn't being found by `gdb`. If I attach to a process with `NUMBA_DEBUGINFO=1` with `lldb`, it does see the debug info, so it's being generated, just `gdb` can't read it for some reason.

The problem is something about the interaction of Numba and gdb, see below for upstream bug.

**Comment by itamarst** [comment]
... but it works in CI on Ubuntu 24.04, which is what I am running. So what is going on? I'm still confused.

**Comment by itamarst** [comment]
`lldb` does get stack traces. `gdb` (on my computer) does not. why.

**Comment by itamarst** [comment]
I filed https://github.com/numba/numba/issues/9817 but still need to do _something_. Try lldb support again? Warn people at minimum? Cry?

**Comment by pythonspeed** [comment]
Supposedly gdb from conda-forge (but not normal Conda!) works.

**Comment by itamarst** [comment]
I guess I could... ship the wheel with a gdb binary? That seems terrible.

**Comment by itamarst** [comment]
Here is the best solution I've come up with so far:

1. Include micromamba in the wheel.
2. Create an env and install gdb=12 on startup.
3. Use that gdb instead of system gdb.
